import { Product } from './types';

export const products: Product[] = [
  {
    id: 'midnight-sneakers',
    name: 'Midnight Drop Sneakers',
    price: 2999,
    originalPrice: 4999,
    discount: 40,
    image: '/placeholder.svg',
    category: 'Fashion',
    subCategory: 'Shoes',
    description: 'Limited edition sneakers dropping at midnight. Premium leather with glow-in-the-dark sole. Only 10 pairs available!',
    stock: 10,
    isFlashSale: true,
    flashSaleStock: 10,
    flashDiscountLimit: 10,
    flashDiscountExtra: 40,
    rating: 4.8,
    reviews: 234,
  },
  {
    id: 'classic-white-tee',
    name: 'Classic White T-Shirt',
    price: 599,
    originalPrice: 999,
    discount: 40,
    image: '/placeholder.svg',
    category: 'Fashion',
    subCategory: 'T-shirts',
    description: 'Premium cotton t-shirt with a perfect fit. Soft breathable fabric for all-day comfort.',
    stock: 50,
    isFlashSale: false,
    rating: 4.5,
    reviews: 1230,
  },
  {
    id: 'casual-hoodie',
    name: 'Casual Hoodie',
    price: 1299,
    originalPrice: 2199,
    discount: 41,
    image: '/placeholder.svg',
    category: 'Fashion',
    subCategory: 'Hoodies',
    description: 'Cozy fleece-lined hoodie perfect for chilly evenings.',
    stock: 30,
    isFlashSale: false,
    rating: 4.6,
    reviews: 876,
  },
  {
    id: 'bt-headphones',
    name: 'Bluetooth Headphones',
    price: 1499,
    originalPrice: 2999,
    discount: 50,
    image: '/placeholder.svg',
    category: 'Electronics',
    subCategory: 'Headphones',
    description: 'Noise-cancelling wireless headphones with 30hr battery life.',
    stock: 25,
    isFlashSale: false,
    rating: 4.7,
    reviews: 2100,
  },
  {
    id: 'smart-watch',
    name: 'Smart Watch',
    price: 3499,
    originalPrice: 5999,
    discount: 42,
    image: '/placeholder.svg',
    category: 'Electronics',
    subCategory: 'Smart Watches',
    description: 'Feature-rich smartwatch with health tracking, GPS, and AMOLED display.',
    stock: 15,
    isFlashSale: false,
    rating: 4.4,
    reviews: 567,
  },
  {
    id: 'table-lamp',
    name: 'Home Table Lamp',
    price: 899,
    originalPrice: 1499,
    discount: 40,
    image: '/placeholder.svg',
    category: 'Home Appliances',
    subCategory: 'Lamp',
    description: 'Elegant modern table lamp with adjustable brightness and warm LED light.',
    stock: 40,
    isFlashSale: false,
    rating: 4.3,
    reviews: 345,
  },
  {
    id: 'denim-jeans',
    name: 'Slim Fit Denim Jeans',
    price: 1199,
    originalPrice: 1999,
    discount: 40,
    image: '/placeholder.svg',
    category: 'Fashion',
    subCategory: 'Jeans',
    description: 'Comfortable stretch denim with a modern slim fit.',
    stock: 35,
    isFlashSale: false,
    rating: 4.5,
    reviews: 980,
  },
  {
    id: 'formal-shirt',
    name: 'Oxford Formal Shirt',
    price: 899,
    originalPrice: 1599,
    discount: 44,
    image: '/placeholder.svg',
    category: 'Fashion',
    subCategory: 'Shirts',
    description: 'Crisp cotton Oxford shirt for a sharp office look.',
    stock: 45,
    isFlashSale: false,
    rating: 4.4,
    reviews: 654,
  },
  {
    id: 'hand-mixer',
    name: 'Kitchen Hand Mixer',
    price: 1299,
    originalPrice: 2499,
    discount: 48,
    image: '/placeholder.svg',
    category: 'Home Appliances',
    subCategory: 'Mixer',
    description: 'Powerful 300W hand mixer with 5 speed settings.',
    stock: 20,
    isFlashSale: false,
    rating: 4.2,
    reviews: 432,
  },
  {
    id: 'steam-iron',
    name: 'Steam Press Iron',
    price: 799,
    originalPrice: 1299,
    discount: 38,
    image: '/placeholder.svg',
    category: 'Home Appliances',
    subCategory: 'Iron',
    description: 'Ceramic soleplate steam iron with anti-drip technology.',
    stock: 30,
    isFlashSale: false,
    rating: 4.1,
    reviews: 289,
  },
  {
    id: 'running-shoes',
    name: 'UltraBoost Running Shoes',
    price: 3999,
    originalPrice: 6499,
    discount: 38,
    image: '/placeholder.svg',
    category: 'Fashion',
    subCategory: 'Shoes',
    description: 'Lightweight responsive cushioning for your daily run.',
    stock: 18,
    isFlashSale: false,
    rating: 4.8,
    reviews: 1567,
  },
  {
    id: 'leather-belt',
    name: 'Genuine Leather Belt',
    price: 499,
    originalPrice: 899,
    discount: 44,
    image: '/placeholder.svg',
    category: 'Fashion',
    subCategory: 'Accessories',
    description: 'Handcrafted genuine leather belt with brushed metal buckle.',
    stock: 60,
    isFlashSale: false,
    rating: 4.3,
    reviews: 778,
  },
];

export const categories = [
  {
    name: 'Fashion',
    subcategories: ['T-shirts', 'Shirts', 'Jeans', 'Hoodies', 'Shoes', 'Accessories'],
    icon: '👗',
  },
  {
    name: 'Electronics',
    subcategories: ['Headphones', 'Smart Watches'],
    icon: '🎧',
  },
  {
    name: 'Home Appliances',
    subcategories: ['Mixer', 'Iron', 'Lamp'],
    icon: '🏠',
  },
];
